version: "3"
services:
    shipmentmanagement:
        image: shipmentmanagement:latest
        entrypoint:
            - /bin/sh
            - "-c"
            - "update-ca-certificates && dotnet EasyDdd.ShipmentManagement.Web.dll"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
            ASPNETCORE_URLS: "https://*:443"
            ASPNETCORE_Kestrel__Certificates__Default__Password: easyddd
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
            TmsDb: "Server=sqlserver,1433; Database=EasyDdd; User Id=SA; Password=SA_Password; trustServerCertificate=true"
        volumes:
            - ./certs/:/usr/local/share/ca-certificates/
            - ./certs/:/https/
        ports:
            - "9000:443"
        depends_on:
            - sqlserver
            - kafka
    billing:
        image: billing:latest
        entrypoint:
            - /bin/sh
            - "-c"
            - "update-ca-certificates && dotnet EasyDdd.Billing.Web.dll"
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
            ASPNETCORE_URLS: "https://*:443"    
            ASPNETCORE_Kestrel__Certificates__Default__Password: easyddd
            ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
            TmsDb: "Server=sqlserver,1433; Database=EasyDdd; User Id=SA; Password=SA_Password; trustServerCertificate=true"
        volumes:
            - ./certs/:/usr/local/share/ca-certificates/
            - ./certs/:/https/
        ports:
            - "9010:443"
        depends_on:
            - sqlserver
            - kafka
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - 1434:1433
        environment: 
            SA_PASSWORD: "SA_Password"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
          - "2181:2181"
    kafka:
      image: wurstmeister/kafka
      ports:
          - "9092:9092"
      environment:
          KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
          KAFKA_CREATE_TOPICS: "shipments:1:1"
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      depends_on:
        - zookeeper