// <auto-generated />
using System;
using EasyDdd.ShipmentManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyDdd.ShipmentManagement.Data.Migrations
{
    [DbContext(typeof(TmsContext))]
    partial class TmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence("DispatchNumbers", "ShipmentManagement")
                .StartsAt(1000L);

            modelBuilder.HasSequence("ShipmentIds", "ShipmentManagement")
                .StartsAt(1000L);

            modelBuilder.Entity("EasyDdd.ShipmentManagement.Core.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("SYSTEM");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Shipments", "ShipmentManagement");
                });

            modelBuilder.Entity("EasyDdd.ShipmentManagement.Core.Shipment", b =>
                {
                    b.OwnsOne("EasyDdd.ShipmentManagement.Core.AppointmentWindow", "ReadyWindow", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("time");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("time");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments", "ShipmentManagement");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("EasyDdd.ShipmentManagement.Core.Dispatch", "DispatchInfo", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("Created")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("datetimeoffset")
                                .HasDefaultValueSql("GETUTCDATE()");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("DispatchDateTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DispatchNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PickupNote")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PickupNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReferenceNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments", "ShipmentManagement");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("EasyDdd.ShipmentManagement.Core.Rate", "CarrierRate", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Carrier")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<decimal>("ChargeTotal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("DiscountAmount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("FuelCharge")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Total")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments", "ShipmentManagement");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");

                            b1.OwnsMany("EasyDdd.ShipmentManagement.Core.Charge", "Charges", b2 =>
                                {
                                    b2.Property<int>("RateShipmentId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"), 1L, 1);

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(450)
                                        .HasColumnType("nvarchar(450)");

                                    b2.HasKey("RateShipmentId", "Id");

                                    b2.ToTable("RateItemCharges", "ShipmentManagement");

                                    b2.WithOwner()
                                        .HasForeignKey("RateShipmentId");
                                });

                            b1.Navigation("Charges");
                        });

                    b.OwnsOne("EasyDdd.ShipmentManagement.Core.Location", "Consignee", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments", "ShipmentManagement");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");

                            b1.OwnsOne("EasyDdd.ShipmentManagement.Core.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("LocationShipmentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Line1")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Line2")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StateAbbreviation")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("LocationShipmentId");

                                    b2.ToTable("Shipments", "ShipmentManagement");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationShipmentId");
                                });

                            b1.OwnsOne("EasyDdd.ShipmentManagement.Core.Contact", "Contact", b2 =>
                                {
                                    b2.Property<int>("LocationShipmentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Email")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Phone")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("LocationShipmentId");

                                    b2.ToTable("Shipments", "ShipmentManagement");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationShipmentId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("Contact")
                                .IsRequired();
                        });

                    b.OwnsOne("EasyDdd.ShipmentManagement.Core.Location", "Shipper", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments", "ShipmentManagement");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");

                            b1.OwnsOne("EasyDdd.ShipmentManagement.Core.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("LocationShipmentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Line1")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Line2")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StateAbbreviation")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("LocationShipmentId");

                                    b2.ToTable("Shipments", "ShipmentManagement");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationShipmentId");
                                });

                            b1.OwnsOne("EasyDdd.ShipmentManagement.Core.Contact", "Contact", b2 =>
                                {
                                    b2.Property<int>("LocationShipmentId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Email")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Phone")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("LocationShipmentId");

                                    b2.ToTable("Shipments", "ShipmentManagement");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationShipmentId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("Contact")
                                .IsRequired();
                        });

                    b.OwnsMany("EasyDdd.ShipmentManagement.Core.ShipmentDetail", "Details", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Class")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("HandlingUnitCount")
                                .HasColumnType("int");

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("IsHazardous")
                                .HasColumnType("bit");

                            b1.Property<string>("PackagingType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Weight")
                                .HasColumnType("int");

                            b1.HasKey("ShipmentId", "Id");

                            b1.HasIndex("Identifier");

                            b1.ToTable("ShipmentDetails", "ShipmentManagement");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsMany("EasyDdd.ShipmentManagement.Core.TrackingEvent", "TrackingHistory", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"), 1L, 1);

                            b1.Property<string>("Comments")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("Occurred")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("ShipmentId", "Id");

                            b1.HasIndex("Type");

                            b1.ToTable("TrackingHistory", "ShipmentManagement");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("CarrierRate");

                    b.Navigation("Consignee")
                        .IsRequired();

                    b.Navigation("Details");

                    b.Navigation("DispatchInfo");

                    b.Navigation("ReadyWindow")
                        .IsRequired();

                    b.Navigation("Shipper")
                        .IsRequired();

                    b.Navigation("TrackingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
